#!/bin/bash

mvn install:install-file -Dfile=target/blackbox-client-0.0.1-SNAPSHOT.jar -DgroupId=blackbox-client -DartifactId=com.kainos.training.blackbox.client -Dversion=0.0.1-SNAPSHOT -Dpackaging=jar